<?php
session_start();
require_once '../../config/conn.php';

// Redirect if not logged in
if (!isset($_SESSION['user_id'])) {
    header("Location: ../../login.php");
    exit();
}

// Verify HR role
$stmt = $pdo->prepare("SELECT name, position FROM users WHERE id = :id");
$stmt->execute([':id' => $_SESSION['user_id']]);
$user = $stmt->fetch(PDO::FETCH_ASSOC);
if ($user['position'] !== 'hr') {
    header("Location: ../../unauthorized.php");
    exit();
}

// Fetch employees for filter
$employees = $pdo->query("SELECT id, name FROM users WHERE position != 'hr' ORDER BY name ASC")->fetchAll(PDO::FETCH_ASSOC);

// Fetch leave types for filter
$leaveTypes = $pdo->query("SELECT id, name FROM leave_types ORDER BY name ASC")->fetchAll(PDO::FETCH_ASSOC);

// Fetch all leave requests
$summary = $pdo->query("
    SELECT lr.id, u.name AS employee_name, lt.name AS leave_type,
           lr.start_date, lr.end_date, lr.applied_at,
           (DATE_PART('day', lr.end_date::timestamp - lr.start_date::timestamp) + 1) AS total_days
    FROM leave_requests lr
    LEFT JOIN users u ON lr.user_id = u.id
    LEFT JOIN leave_types lt ON lr.leave_type_id = lt.id
    ORDER BY lr.applied_at DESC
")->fetchAll(PDO::FETCH_ASSOC);
?>

<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>HR Leave Reports | Teraju LMS</title>
<link rel="stylesheet" href="../../assets/css/style.css">
<style>
body { font-family: Arial, sans-serif; }
.layout { display: flex; }
.main-content { flex: 1; padding: 20px; }
.card { background: #fff; padding: 20px; border-radius: 10px; box-shadow: 0 2px 8px rgba(0,0,0,0.1); }
.filter-bar { display: flex; gap: 10px; flex-wrap: wrap; margin-bottom: 20px; }
.filter-bar select, .filter-bar input { padding: 6px 10px; border-radius: 6px; border: 1px solid #cbd5e1; }
.filter-bar button { padding: 6px 12px; border:none; border-radius:6px; background:#3b82f6; color:#fff; cursor:pointer; }
.leave-table { width: 100%; border-collapse: collapse; margin-top:10px; }
.leave-table th, .leave-table td { border:1px solid #ddd; padding:8px; text-align:left; }
.leave-table th { background:#f3f4f6; }
.print-header { text-align: center; margin-bottom: 10px; }
.print-meta { font-size:0.85rem; color:#555; margin-bottom: 10px; }
@media print {
  body * { visibility:hidden; }
  .print-area, .print-area * { visibility:visible; }
  .print-area { position:absolute; top:0; left:0; width:100%; }
}
</style>
</head>
<body>
<div class="layout">
  <?php include 'sidebar.php'; ?>
    <header>
        <h1>Leave Management System</h1>
    </header>

  <main class="main-content">
    <div class="card">
      <h2>HR Leave Reports</h2>

      <!-- Filter Bar -->
      <div class="filter-bar">
        <select id="employeeFilter">
          <option value="">All Employees</option>
          <?php foreach($employees as $e): ?>
            <option value="<?= htmlspecialchars($e['name']) ?>"><?= htmlspecialchars($e['name']) ?></option>
          <?php endforeach; ?>
        </select>

        <select id="typeFilter">
          <option value="">All Leave Types</option>
          <?php foreach($leaveTypes as $lt): ?>
            <option value="<?= htmlspecialchars($lt['name']) ?>"><?= htmlspecialchars($lt['name']) ?></option>
          <?php endforeach; ?>
        </select>

        <input type="date" id="startDateFilter" placeholder="Start Date">
        <input type="date" id="endDateFilter" placeholder="End Date">

        <button onclick="printReport()">🖨 Print</button>
      </div>

      <!-- Printable area -->
      <div class="print-area">
        <div class="print-header">
          <h3>Teraju HR — Leave Report</h3>
          <p class="print-meta">Generated by: <?= htmlspecialchars($user['name']) ?> | Date: <?= date('Y-m-d') ?></p>
          <hr>
        </div>

        <table class="leave-table" id="reportTable">
          <thead>
            <tr>
              <th>Employee</th>
              <th>Leave Type</th>
              <th>Start Date</th>
              <th>End Date</th>
              <th>Total Days</th>
              <th>Requested On</th>
            </tr>
          </thead>
          <tbody>
            <?php foreach($summary as $row): ?>
              <tr>
                <td><?= htmlspecialchars($row['employee_name']) ?></td>
                <td><?= htmlspecialchars($row['leave_type']) ?></td>
                <td><?= htmlspecialchars($row['start_date']) ?></td>
                <td><?= htmlspecialchars($row['end_date']) ?></td>
                <td><?= (int)$row['total_days'] ?></td>
                <td><?= htmlspecialchars(date('Y-m-d', strtotime($row['applied_at']))) ?></td>
              </tr>
            <?php endforeach; ?>
          </tbody>
        </table>
      </div>

    </div>
  </main>
</div>

<script>
// Filter table function
function filterTable() {
  const emp = document.getElementById('employeeFilter').value.toLowerCase();
  const type = document.getElementById('typeFilter').value.toLowerCase();
  const start = document.getElementById('startDateFilter').value;
  const end = document.getElementById('endDateFilter').value;

  const rows = document.querySelectorAll('#reportTable tbody tr');
  rows.forEach(row => {
    const name = row.cells[0].textContent.toLowerCase();
    const leaveType = row.cells[1].textContent.toLowerCase();
    const startDate = row.cells[2].textContent;
    const endDate = row.cells[3].textContent;

    let show = true;
    if(emp && !name.includes(emp)) show = false;
    if(type && !leaveType.includes(type)) show = false;
    if(start && endDate < start) show = false;
    if(end && startDate > end) show = false;

    row.style.display = show ? '' : 'none';
  });
}

// Print report
function printReport() {
  window.print();
}

// Add event listeners to filters
document.getElementById('employeeFilter').addEventListener('change', filterTable);
document.getElementById('typeFilter').addEventListener('change', filterTable);
document.getElementById('startDateFilter').addEventListener('change', filterTable);
document.getElementById('endDateFilter').addEventListener('change', filterTable);
</script>
<script src="../../assets/js/sidebar.js"></script>

</body>
</html>
